sudo: required
dist: trusty

language: node_js
node_js:
- '6'

addons: 
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta

cache:
  directories:
  - node_modules
  - example/node_modules
  - $(npm config get prefix)/bin/ng
  - $(npm config get prefix)/bin/karma

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

before_script:
- ./node_modules/angular-cli/bin/ng -v || npm install angular-cli@1.0.0-beta.18
- ./node_modules/karma/bin/karma --version || npm install karma
- cd example
- npm install
- ../node_modules/angular-cli/bin/ng build

script: ../node_modules/karma/bin/karma start karma.conf.js --single-run
